services:
  postgres:
    image: postgres:16
    container_name: project-backend-group-1-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-project_dev}
      POSTGRES_USER: ${POSTGRES_USER:-project}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-project}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-project} -d ${POSTGRES_DB:-project_dev}"]
      interval: 10s
      timeout: 5s
      retries: 5
  minio:
    image: minio/minio
    container_name: project-minio
    restart: unless-stopped
    environment:
        MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
        MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    ports:
      - "${MINIO_API_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"


volumes:
  postgres_data:
  minio_data:
